Add 404 and update navbar
donkey-engine/donkey-engine-ui pull request #35
Opened 2021-06-13 21:23 UTC by BehindLoader

2021-06-14 07:01 UTC, tmcgroul commented
@BehindLoader a u tebya takoy owibki ne bilo?
```
ERROR in src/components/NotFound.vue:34:19
TS2339: Property 'icons' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, EmitsOptions, {}, {}, false, ComponentOptionsBase<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, EmitsOptions, string, {}>>'.
    32 |   computed: {
    33 |     currentIcon() {
  > 34 |       return this.icons[this.iconIndex]
       |                   ^^^^^
    35 |     }
    36 |   },
    37 |   created() {

ERROR in src/components/NotFound.vue:34:30
TS2339: Property 'iconIndex' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, EmitsOptions, {}, {}, false, ComponentOptionsBase<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, EmitsOptions, string, {}>>'.
    32 |   computed: {
    33 |     currentIcon() {
  > 34 |       return this.icons[this.iconIndex]
       |                              ^^^^^^^^^
    35 |     }
    36 |   },
    37 |   created() {
    ```

2021-06-14 13:42 UTC, BehindLoader commented
@tmcgroul очень странно. я тип добавил, вроде пропало

2021-06-14 17:12 UTC, tmcgroul requested changes

2021-06-14 17:12 UTC, tmcgroul commented on src/App.vue
> +  <navbar @create-server="servers.push($event)" />
vot tut owibka
i ne ochevidno kak ee ispravit'....

2021-06-14 17:38 UTC, tmcgroul commented on src/App.vue
> +  <navbar @create-server="servers.push($event)" />
nu mojno poka ob'yavit' servers v App.vue i propsami kidat' v dashboard

2021-06-20 21:22 UTC, tmcgroul commented on src/store.ts
> +interface Server {}
В interfaces.ts есть нужный интерфейс

2021-06-20 21:31 UTC, tmcgroul approved these changes

2021-06-20 21:31 UTC, merged